import { Customer, DocumentTypes } from '../../shared/models/customers';

export const CUSTOMERS_MOCK: Customer[] = [
  {
    id: 1,
    documentType: DocumentTypes.CE,
    documentNumber: '10102020',
    fullName: 'Carlos Alberto Rodríguez',
    email: 'carlos.rod@mail.com',
  },
  {
    id: 2,
    documentType: DocumentTypes.PAS,
    documentNumber: '850493',
    fullName: 'Elena Schmidt',
    email: 'elena.s@inter.de',
  },
  {
    id: 3,
    documentType: DocumentTypes.PAS,
    documentNumber: '52889102',
    fullName: 'Diana Marcela Gómez',
    email: 'diana.gomez@empresa.co',
  },
  {
    id: 4,
    documentType: DocumentTypes.CC,
    documentNumber: '1032456789',
    fullName: 'Andrés Felipe Arias',
    email: 'af.arias@servicios.com',
  },
  {
    id: 5,
    documentType: DocumentTypes.PAS,
    documentNumber: 'P7765432',
    fullName: 'John Walker',
    email: 'j.walker@traveler.com',
  },
  {
    id: 6,
    documentType: DocumentTypes.CC,
    documentNumber: '20456789',
    fullName: 'Paola Andrea Martínez',
    email: 'paola.mtz@bogota.co',
  },
  {
    id: 7,
    documentType: DocumentTypes.CE,
    documentNumber: '1015432111',
    fullName: 'Ricardo Jorge Sierra',
    email: 'r.sierra@banca.com',
  },
  {
    id: 8,
    documentType: DocumentTypes.CE,
    documentNumber: '990876',
    fullName: 'Marie Curie',
    email: 'm.curie@science.fr',
  },
  {
    id: 9,
    documentType: DocumentTypes.CC,
    documentNumber: '1020304050',
    fullName: 'Santiago Ospina',
    email: 'santi.ospina@deportes.com',
  },
  {
    id: 10,
    documentType: DocumentTypes.CC,
    documentNumber: '32456781',
    fullName: 'Lucía Fernanda Castro',
    email: 'lucia.castro@diseno.com',
  },
  {
    id: 11,
    documentType: DocumentTypes.CC,
    documentNumber: '1077889900',
    fullName: 'Mateo Valencia',
    email: 'm.valencia@tech.io',
  },
  {
    id: 12,
    documentType: DocumentTypes.PAS,
    documentNumber: 'A1234567',
    fullName: 'Yuki Tanaka',
    email: 'y.tanaka@japan.jp',
  },
  {
    id: 13,
    documentType: DocumentTypes.CC,
    documentNumber: '80123456',
    fullName: 'Gustavo Adolfo Becquer',
    email: 'g.becquer@letras.es',
  },
  {
    id: 14,
    documentType: DocumentTypes.CC,
    documentNumber: '1000234567',
    fullName: 'Valentina Quintero',
    email: 'vale.quin@estudio.edu.co',
  },
  {
    id: 15,
    documentType: DocumentTypes.CE,
    documentNumber: '765432',
    fullName: 'Hans Zimmer',
    email: 'h.zimmer@music.com',
  },
];
